### ISSUE TITLE
Clarify definition of a "Closed" data center

### ISSUE THREAD

**Issue by Hotdog-Willie** [WhiteHouse/datacenters#29]
Goal 3: Closed Data centers (near the top of page 8) states:

> "In all cases, the term “closed” for data centers shall refer exclusively to tiered or non-tiered data centers that: a) **no longer consume power**; or b) no longer house physical servers (whether in a production, test, stage, development, or any other environment)."

It is suggested that the definition be clarified by adding "for the hosting of IT services" at the end of "no longer consume power".  In some instances, data centers are in multipurpose buildings, where the space originally housing the data center may still be in an agency's inventory (consuming some power for non-IT purposes) even if the data center is no longer there.

**Comment by wjwooley** [comment]
In the FDCCI DataPoint Portal Frequently Asked Questions (FAQ) document, clarification was given to closed data centers as follows: "If a portion of the facility/room will be designated as a telecommunications and infrastructure equipment room, equipment such as print servers, domain controllers, firewalls, or network switches are not required to be removed for the facility to be considered closed."  Is this previous OMB guidance still valid?
If not, will the data centers that were closed based on the previous guidance have to be re-opened and/or will the rooms that were not included because of the exception have to be added?
