### ISSUE TITLE
Should cloud services be excluded from DCOI?

### ISSUE THREAD

**Issue by IsaacN99** [WhiteHouse/datacenters#40]
Cloud services are essentially a suite of services running over a physical data center infrastructure.  When combined with the Cloud First policy, it would seem that DCOI (with a cloud exemption) would seek to quickly optimize data centers while simultaneously creating a growing portfolio of non-optimized data centers, existing behind the cloud label.

Cloud services should be included in this memorandum, should require PUE reporting, and be viewed as physical data centers - since - that is what they are underneath the set of services that reclassify the asset as a cloud service vs. a physical data center.

**Comment by MovieQuoter** [comment]
Generally agree with this comment though would further clarify that any private government cloud should almost certainly not be excluded from the optimization goals - whether private-sector-provided or government-owned.

**Comment by wjwooley** [comment]
Since one of the primary objectives of the DCOI is to encourage agencies to migrate to Cloud Services, recommend excluding all performance metrics from Cloud Services provisioned from a commercial service provider.  As stated below, EO13693 guidance sufficiently addresses this issue.
"Agencies are encouraged to use contracted data center services, including cloud services, which are provided through data centers which meet the above requirements for new data centers (e.g., a PUE of at most 1.4, but preferably at most 1.2).  Agencies must include procurement preference for data centers with the lowest demonstrated PUE and should specify annual reporting on PUE from contracted data center services, including cloud services, if available."
